# .buildDockerBranchDevelopment, .buildDockerBranchMaster and .buildDockerBranchStage require following variables:
#    GCLOUD_PROJECT_ID: 
#    GCLOUD_SA_KEY: base64-encoded SA key
#    SSH_KEY: base64-encoded RSA private key
#    IMAGE_NAME: name of the local image
#    IMAGE_TAG: tag for local and remote images
#
# Also configure DOCKER_GCR_IMAGE

.buildScript: &buildScript
  - gcr-init
  - docker build --build-arg SSH_KEY -t ${IMAGE_NAME}:${IMAGE_TAG} .
  - docker tag ${IMAGE_NAME}:${IMAGE_TAG} eu.gcr.io/${GCLOUD_PROJECT_ID}/${PROJECT_NAME}/${APP_NAME}:${IMAGE_TAG}
  - docker push eu.gcr.io/${GCLOUD_PROJECT_ID}/${PROJECT_NAME}/${APP_NAME}:${IMAGE_TAG}

.buildDockerBranchDevelopment:
  image: ${DOCKER_GCR_IMAGE}
  stage: build
  script: *buildScript
  only:
    refs: ["development"]
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  cache: {}
      
.buildDockerBranchMaster:
  image: ${DOCKER_GCR_IMAGE}
  stage: build
  script: *buildScript
  only:
    refs: ["master"]
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  cache: {}

.buildDockerBranchStage:
  image: ${DOCKER_GCR_IMAGE}
  stage: build
  script: *buildScript
  only:
    refs: ["stage"]
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  cache: {}
      
# .aglioDocsUpload requires following variables:
#   GCLOUD_PROJECT_ID:
#   GCLOUD_SA_KEY:
#   AGLIO_DOCS_DIRECTORY:
#   GCS_BUKET:
#   GCS_PREFIX:

# Please note these jobs requires "fetch" to be run before as it they use
# pre-downloaded NPM packages
# https://github.com/AckeeDevOps/gitlabci-templates/blob/master/templates/backend/nodejs/fetch.yml

# Your .gitlab-ci.yml should also have:
# cache:
#   key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

.aglioDocsUpload:
  stage: build
  image: ${AGLIO_UPLOADER_IMAGE}
  script:
    - mkdir -p ${AGLIO_DOCS_DIRECTORY}
    - npm run docs
    - rclone-upload
