.buildBranch:
  image: ${NODE_IMAGE}
  stage: build
  variables:
    # BUILD_COMMAND_CURRENT
    # BUILD_DIRECTORY_CURRENT
  script:
    - eval ${BUILD_COMMAND_DEVELOPMENT}
  artifacts:
    expire_in: 30m
    paths:
      - ${BUILD_DIRECTORY_DEVELOPMENT}
  # also specify
  # only:
  #   variables:
  #     - $CI_PIPELINE_SOURCE == "push"
  #   refs: ["<branch name>"]
