.buildBranch:
  image: ${NODE_IMAGE}
  stage: build
  variables:
    # specify following variables while extending .buildBranch
    # BUILD_COMMAND_CURRENT
    # BUILD_DIRECTORY_CURRENT
  before_script:
    - mkdir ~/.ssh/
    - echo ${SSH_KEY} | base64 -d > ~/.ssh/id_rsa
    - chmod 0400 ~/.ssh/id_rsa
    - eval `ssh-agent -s` && ssh-add ~/.ssh/id_rsa
  script:
    - eval ${BUILD_COMMAND_CURRENT}
  artifacts:
    expire_in: 30m
    paths:
      - ${BUILD_DIRECTORY_CURRENT}
  # also specify
  # only:
  #   variables:
  #     - $CI_PIPELINE_SOURCE == "push"
  #   refs: ["<branch name>"]
