.beforeScriptHelmUpload: &beforeScriptHelmUpload
  #  validate input
  - wget -q -O - https://raw.githubusercontent.com/AckeeDevOps/gitlabci-templates/master/scripts/devops/helm/validate_upload.sh | sh
  # /validate input
  - apk add ca-certificates git > /dev/null 2>&1
  - wget ${HELM_BINARIES_URL} -O helm.tar.gz > /dev/null 2>&1
  - tar -xvf helm.tar.gz > /dev/null 2>&1
  - mv linux-amd64/helm /usr/local/bin
  - rm -rf linux-amd64 helm.tar.gz
  - helm init --client-only > /dev/null 2>&1
  - helm plugin install https://github.com/chartmuseum/helm-push > /dev/null 2>&1
  - helm repo add --username ${HELM_REPOSITORY_USERNAME} --password ${HELM_REPOSITORY_PASSWORD} ${HELM_REPOSITORY_NAME} ${HELM_REPOSITORY_URL} > /dev/null 2>&1
  
.scriptHelmUpload: &scriptHelmUpload
  # replace version in Chart.yaml
  - "sed -i \"s/version: .*/version: ${CI_COMMIT_TAG}/g\" chart/Chart.yaml"
  # show version in the console
  - grep "version:" chart/Chart.yaml
  # push chart to the repository
  - helm push chart ${HELM_REPOSITORY_NAME}
   
.helmUploadTag:
  stage: upload
  image: alpine
  before_script: *beforeScriptHelmUpload
  script: *scriptHelmUpload
  only:
    variables:
      - $CI_COMMIT_TAG
