.beforeScriptHelmUpload: &beforeScriptHelmUpload
  #  validate input
  - wget -q -O - https://raw.githubusercontent.com/AckeeDevOps/gitlabci-templates/master/scripts/devops/helm/validate.sh | sh
  # /validate input
  #  install and configure Helm
  - wget -q -O - https://raw.githubusercontent.com/AckeeDevOps/gitlabci-templates/master/scripts/devops/helm/install_helm_alpine.sh | sh
  # /install and configure Helm
  
.scriptHelmUpload: &scriptHelmUpload
  # replace version in Chart.yaml
  - "sed -i \"s/version: .*/version: ${CI_COMMIT_TAG}/g\" chart/Chart.yaml"
  # replace chart name
  - "sed -i \"s/name: .*/name: ${HELM_CHART_NAME}/g\" chart/Chart.yaml"
  # show version in the console
  - grep "version:" chart/Chart.yaml
  # push chart to the repository
  - helm push chart ${HELM_REPOSITORY_NAME}
   
.helmUploadTag:
  stage: upload
  image: alpine
  before_script: *beforeScriptHelmUpload
  script: *scriptHelmUpload
  only:
    variables:
      - $CI_COMMIT_TAG
