.beforeScriptDeploy: &preDeploySecrets
  - export VAULTIER_RUN_CAUSE=delivery
  - export VAULTIER_OUTPUT_FORMAT=helm
  - export VAULTIER_SECRET_OUTPUT_PATH=/tmp/secrets.json
  - export VAULTIER_BRANCH=${CI_COMMIT_REF_NAME}

.deployScriptSecrets: &deployScriptSecrets
  - wget https://raw.githubusercontent.com/AckeeDevOps/gitlabci-templates/master/scripts/helm_deploy_secrets.sh -O /usr/local/bin/helm-deploy
  - chmod +x /usr/local/bin/helm-deploy
  - gke-init
  - vaultier
  - helm-deploy

.deployBranchSecrets:
  image: ${HELMER_IMAGE}
  stage: deploy
  before_script: *preDeploySecrets
  script: *deployScriptSecrets
  variables:
    #GCLOUD_SA_KEY: must be specified globally
    #VAULTIER_VAULT_ADDR: must be specified globally
    #VAULTIER_VAULT_TOKEN: must be specified globally
  allow_failure: false # important for manual jobs

.deployBranchSecretsMaster:
  extends: .deployBranchSecrets
  variables:    
    GCLOUD_PROJECT_ID: ${GCLOUD_PROJECT_ID_PRODUCTION}
    GCLOUD_GKE_CLUSTER_NAME: ${GCLOUD_GKE_CLUSTER_PRODUCTION}
    GCLOUD_GKE_ZONE: ${GCLOUD_GKE_ZONE_PRODUCTION}
    GCLOUD_GKE_NAMESPACE: ${GCLOUD_GKE_NAMESPACE_PRODUCTION}    
    HELM_BASE_VALUES: helm/values/production.yaml
  only:
    refs: ["master"]
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  environment:
    name: production
  when: manual
    
.deployBranchSecretsStage:
  extends: .deployBranchSecrets
  variables:    
    GCLOUD_PROJECT_ID: ${GCLOUD_PROJECT_ID_STAGE}
    GCLOUD_GKE_CLUSTER_NAME: ${GCLOUD_GKE_CLUSTER_STAGE}
    GCLOUD_GKE_ZONE: ${GCLOUD_GKE_ZONE_STAGE}
    GCLOUD_GKE_NAMESPACE: ${GCLOUD_GKE_NAMESPACE_STAGE}    
    HELM_BASE_VALUES: helm/values/stage.yaml
  only:
    refs: ["stage"]
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  environment:
    name: stage
  when: manual
    
.deployBranchSecretsDevelopment:
  extends: .deployBranchSecrets
  variables:    
    GCLOUD_PROJECT_ID: ${GCLOUD_PROJECT_ID_DEVELOPMENT}
    GCLOUD_GKE_CLUSTER_NAME: ${GCLOUD_GKE_CLUSTER_DEVELOPMENT}
    GCLOUD_GKE_ZONE: ${GCLOUD_GKE_ZONE_DEVELOPMENT}
    GCLOUD_GKE_NAMESPACE: ${GCLOUD_GKE_NAMESPACE_DEVELOPMENT}    
    HELM_BASE_VALUES: helm/values/development.yaml
  only:
    refs: ["development"]
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  environment:
    name: development
