.beforeDocumentation: &preDocumentation
  #  validate input
  - wget -q -O - https://raw.githubusercontent.com/AckeeDevOps/gitlabci-templates/master/scripts/backend/nodejs/docker/validate_documentation.sh | sh
  # /validate input
  #  install uploader script
  - wget https://raw.githubusercontent.com/AckeeDevOps/gitlabci-templates/master/scripts/backend/nodejs/common/rclone-upload.sh -O /usr/local/bin/rclone-upload > /dev/null 2>&1
  - chmod +x /usr/local/bin/rclone-upload
  # /install uploader script
  #  install rclone
  - wget -q -O - https://raw.githubusercontent.com/AckeeDevOps/gitlabci-templates/master/scripts/backend/nodejs/common/rclone-install.sh | sh
  # /install rclone
  - npm set unsafe-perm true
  - npm set progress=false
  - npm set loglevel=error
  - export JOBS=max

.aglioDocsUpload:
  stage: documentation
  image: ${NODE_IMAGE}
  variables:
    GCLOUD_PROJECT_ID: ${GCLOUD_PROJECT_ID_DOCUMENTATION}
    #GCLOUD_SA_KEY: must be specified globally
    #AGLIO_DOCS_DIRECTORY: must be specified globally
    #GCS_BUKET: must be specified globally
    #GCS_PREFIX: must be specified globally
  before_script: *preDocumentation
  script:
    - mkdir -p ${AGLIO_DOCS_DIRECTORY}
    - npm install
    - npm run docs
    - rclone-upload

.aglioDocsUploadDelivery:
  extends: .aglioDocsUpload
  only:
    variables:
      - $CI_PIPELINE_SOURCE == "push"
    refs: ["master", "stage", "development"]

.aglioDocsUploadMergeRequest:
  extends: .aglioDocsUpload
  only: ["merge_requests"]
