.beforeBuild: &preBuild
  #  Validate provided variables
  - wget -q -O - https://raw.githubusercontent.com/AckeeDevOps/gitlabci-templates/master/scripts/backend/go/kubernetes/validate_build_docker.sh | sh
  # /Validate provided variables
  
.buildScript: &buildScript
  - gcr-init
  - docker build --build-arg SSH_KEY -t ${IMAGE_NAME}:${IMAGE_TAG} .
  - docker tag ${IMAGE_NAME}:${IMAGE_TAG} eu.gcr.io/${GCLOUD_PROJECT_ID}/${PROJECT_NAME}/${APP_NAME}-${CI_COMMIT_REF_NAME}:${IMAGE_TAG}
  - docker push eu.gcr.io/${GCLOUD_PROJECT_ID}/${PROJECT_NAME}/${APP_NAME}-${CI_COMMIT_REF_NAME}:${IMAGE_TAG}

.buildDockerBranch:
  image: ${DOCKER_GCR_IMAGE}
  stage: build
  before_script: *preBuild
  script: *buildScript
